### ISSUE TITLE
How to run this with docker-compose 

### ISSUE THREAD

**Issue by mominoes** [codingtony/docker-impala#5]
I'm trying to add this as a service in my docker-compose.yml file, and run it with `docker-compose run --service-ports impala`. However, when doing this, I am unable to access the datanode web UI at localhost:50075, and when running `hadoop fs -put  /some/file.ext  /tmp/somefile.txt`, it says there are 0 datanodes running. 

Running with `docker run` instead works fine. My docker-compose.yml file is below. Any thoughts on why using docker-compose fails to run a datanode correctly?

```
version: '3.7'
services:
  impala:
    image: codingtony/impala
    ports: 
    - 9000:9000
    - 50010:50010
    - 50020:50020
    - 50070:50070 
    - 50075:50075 
    - 21000:21000 
    - 21050:21050 
    - 25000:25000 
    - 25010:25010 
    - 25020:25020
    stdin_open: true
    tty: true
    command: /start-bash.sh
```
For reference, I created this docker-compose.yml file based on the command provided in this repo's README.md: `docker run --rm  -ti  -p 9000:9000 -p 50010:50010 -p 50020:50020 -p 50070:50070 -p 50075:50075 -p 21000:21000 -p 21050:21050 -p 25000:25000 -p 25010:25010 -p 25020:25020 codingtony/impala /start-bash.sh`
